# Generated by Django 2.2.3 on 2019-08-12 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='itemType',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='itemType',
        ),
        migrations.AddField(
            model_name='inventory',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.Category'),
            preserve_default=False,
        ),
    ]
