# Generated by Django 2.2.3 on 2019-08-12 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20190812_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='item',
            new_name='name',
        ),
    ]
