# Generated by Django 2.2.3 on 2019-07-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(verbose_name='Age')),
                ('case_no', models.CharField(max_length=6, unique=True)),
            ],
        ),
    ]
