# Generated by Django 2.2.3 on 2019-08-23 19:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='patient',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 8, 23, 19, 47, 6, 174775, tzinfo=utc), verbose_name='date'),
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='next_of_kin',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='occupation',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
