# Generated by Django 2.2.3 on 2019-07-31 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('patients', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_placement', models.DateTimeField(verbose_name='order placed')),
                ('time_of_fulfilment', models.DateTimeField(verbose_name='order fulfiled')),
                ('status', models.CharField(choices=[('p', 'placed'), ('s', 'seen'), ('f', 'fulfiled')], max_length=1)),
                ('items', models.ManyToManyField(to='inventory.Inventory')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.Patient')),
            ],
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='itemType',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
