# Generated by Django 2.2.3 on 2019-08-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190731_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time_of_fulfilment',
            field=models.DateTimeField(blank=True, verbose_name='order fulfiled'),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_of_placement',
            field=models.DateTimeField(editable=False, verbose_name='order placed'),
        ),
    ]
