# Generated by Django 2.2.3 on 2019-08-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20190802_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='time_of_fulfilment',
        ),
        migrations.AddField(
            model_name='order',
            name='time_of_fulfillment',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='order fulfilled'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('p', 'placed'), ('s', 'seen'), ('f', 'fulfilled')], default='p', max_length=1),
        ),
    ]
